name: toutcas
description: "En tout cas, Ã§a fonctionne. Nothing Stored, Nothing Shared, Burn-After-Use AI Assistant"
publish_to: 'none'  
version: 1.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  flutter_resizable_container: ^4.2.0
  shared_preferences: ^2.5.3
  file_picker: ^10.3.7
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1 # Platform: Linux/macOS/Windows 
  dio: ^5.9.0  
  gpt_markdown: ^1.1.4
  path_provider: ^2.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-logo.png"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
 
  assets: 
    - assets/images/ 

